version: '3.9'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db-multiple
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - ms-network
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init-multiple-db:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: redis-shared
    ports:
      - "6379:6379"
    networks:
      - ms-network
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"] # persistens üçün

networks:
  ms-network:
    driver: bridge

volumes:
  pg-data:
  redis-data:
