version: '3.9'

services:
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - ms-network
    volumes:
      - user-db-data:/var/lib/postgresql/data

  order-db:
    image: postgres:15
    container_name: order-db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    networks:
      - ms-network
    volumes:
      - order-db-data:/var/lib/postgresql/data

  payment-db:
    image: postgres:15
    container_name: payment-db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    networks:
      - ms-network
    volumes:
      - payment-db-data:/var/lib/postgresql/data

networks:
  ms-network:
    driver: bridge

volumes:
  user-db-data:
  order-db-data:
  payment-db-data:
