spring:
  application:
    name: payment-service


  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083
