spring:
  application:
    name: saga-service

  datasource:
    url: jdbc:postgresql://localhost:5432/saga_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8086