spring:
  application:
    name: ms-actuator


management:
  endpoint:
    health:
      probes:
        enabled: true # Readiness v? Liveness-i aktiv edir
  endpoints:
    web:
      exposure:
        include: health,info


server:
  port: 8088
