spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081