spring:
  application:
    name: ms-auth-service

  data:
    redis:
      host: redis
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8084
