spring:
  application:
    name: circuit-breaker-pattern-test-service


#resilience4j:
#  circuitbreaker:
#    instances:
#      paymentService:
#        registerHealthIndicator: true
#        slidingWindowSize: 10
#        failureRateThreshold: 50
#        waitDurationInOpenState: 5s
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowType: COUNT_BASED

resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED



management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8087
